In [415]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [416]:
data = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')

In [417]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [418]:
data = np.array(data)
m,n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
y_dev = data_dev[0]
x_dev = data_dev[1:n]
x_dev = x_dev/255.

data_train = data[1000:m].T
y_train = data_train[0]
x_train = data_train[1:n]
x_train = x_train/255.
print(x_train.shape)


(784, 41000)


In [419]:
y_train

array([7, 8, 3, ..., 3, 9, 4])

In [420]:
def initialize():
    w1 = np.random.rand(10,784) - 0.5
    b1 = np.random.rand(10,1) - 0.5
    w2 = np.random.rand(10,10) - 0.5
    b2 = np.random.rand(10,1) - 0.5
    return w1,b1,w2,b2

In [421]:
def ReLU(z):
    return np.maximum(z,0)

In [422]:
def softmax(z):
    return np.exp(z)/ sum(np.exp(z))

In [423]:
def forward_propogation(w1,b1,w2,b2,x):
    z1 = w1.dot(x) + b1
    a1 = ReLU(z1)
    z2 = w2.dot(a1)+ b2
    a2 = softmax(z2)
    return z1,a1,z2,a2

In [424]:
def deriv_ReLU(z):
    return z > 0;

In [425]:
def back_propogation(z1,a1,z2,a2,w1,w2,x,y):
    linear_y = np.zeros((y.size,y.max()+1))
    linear_y[np.arange(y.size),y] = 1
    linear_y = linear_y.T
    dz2 = a2 - linear_y
    dw2 = (1/m)*dz2.dot(a1.T)
    db2 = (1/m) *np.sum(dz2)
    dz1 = w2.T.dot(dz2) * deriv_ReLU(z1)
    dw1 = 1/m * dz1.dot(x.T)
    db1 = 1/m * np.sum(dz1)
    return dw1,db1,dw2,db2

In [426]:
def update_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha):
    w1 = w1 - alpha*dw1
    b1 = b1 - alpha*db1
    w2 = w2 - alpha*dw2
    b2 = b2 - alpha*db2
    return w1,b1,w2,b2

In [427]:
def get_predictions(a2):
    return np.argmax(a2,0)
def get_accuracy(predictions,y):
    print(predictions,y)
    return np.sum(predictions == y) / y.size

In [428]:
def gradient_descent(x,y,alpha,iterations):
    w1,b1,w2,b2 = initialize()
    for i in range(iterations):
        z1,a1,z2,a2 = forward_propogation(w1,b1,w2,b2,x)
        dw1,db1,dw2,db2 = back_propogation(z1,a1,z2,a2,w1,w2,x,y)
        w1,b1,w2,b2 = update_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha)
        if i% 10 == 0:
            print("Iteration : ",i)
            print("Accuracy : ",get_accuracy(get_predictions(a2),y))
    return w1,b1,w2,b2
    
    

In [429]:
w1,b1,w2,b2 = gradient_descent(x_train,y_train,0.10,1000)

Iteration :  0
[4 2 2 ... 4 7 8] [7 8 3 ... 3 9 4]
Accuracy :  0.06585365853658537
Iteration :  10
[4 4 8 ... 4 9 8] [7 8 3 ... 3 9 4]
Accuracy :  0.25526829268292683
Iteration :  20
[4 4 8 ... 2 9 8] [7 8 3 ... 3 9 4]
Accuracy :  0.36702439024390243
Iteration :  30
[4 4 1 ... 2 9 8] [7 8 3 ... 3 9 4]
Accuracy :  0.44426829268292684
Iteration :  40
[4 3 1 ... 2 9 8] [7 8 3 ... 3 9 4]
Accuracy :  0.5014634146341463
Iteration :  50
[4 3 1 ... 2 9 4] [7 8 3 ... 3 9 4]
Accuracy :  0.5459268292682927
Iteration :  60
[4 3 1 ... 2 9 4] [7 8 3 ... 3 9 4]
Accuracy :  0.5815853658536585
Iteration :  70
[4 8 1 ... 2 9 4] [7 8 3 ... 3 9 4]
Accuracy :  0.6123414634146341
Iteration :  80
[4 8 3 ... 2 9 4] [7 8 3 ... 3 9 4]
Accuracy :  0.6367560975609756
Iteration :  90
[9 8 3 ... 2 9 4] [7 8 3 ... 3 9 4]
Accuracy :  0.6581707317073171
Iteration :  100
[9 8 3 ... 2 9 4] [7 8 3 ... 3 9 4]
Accuracy :  0.6765365853658537
Iteration :  110
[9 8 3 ... 2 9 4] [7 8 3 ... 3 9 4]
Accuracy :  0.6917317073170731

After 1000 Iterations **Test Accuracy ~ 88% **


In [435]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_propogation(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_train[:, index, None]
    prediction = make_predictions(X_train[:, index, None], W1, b1, W2, b2)
    label = Y_train[index]
    print("Prediction: ", prediction)
    print("Label: ", label)
    
    current_image = current_image.reshape((28, 28)) * 255
    plt.gray()
    plt.imshow(current_image, interpolation='nearest')
    plt.show()

In [436]:
dev_predictions = make_predictions(x_dev, w1, b1, w2, b2)
get_accuracy(dev_predictions, y_dev)

[0 6 0 9 1 5 3 9 0 2 6 0 2 1 6 4 5 2 2 9 5 4 9 6 5 1 1 3 4 3 7 5 1 2 8 3 4
 6 9 7 4 4 2 6 7 8 8 9 7 0 6 0 5 0 4 6 6 2 4 7 0 8 4 0 5 0 8 2 1 6 1 8 8 3
 2 7 8 5 0 9 4 1 3 3 1 8 3 0 1 1 4 5 3 2 6 7 6 5 0 8 5 8 6 1 4 4 9 7 2 7 7
 6 7 5 2 7 6 3 2 9 3 4 7 2 7 2 3 1 4 9 9 7 5 6 7 6 2 0 9 4 8 0 7 8 7 4 1 5
 7 0 3 0 4 4 9 3 3 1 7 7 8 4 1 5 7 6 7 9 3 8 7 7 0 8 8 2 6 1 2 6 0 3 4 1 6
 9 5 0 6 7 0 5 7 0 6 5 1 9 9 8 9 6 5 4 8 8 7 1 7 2 4 9 3 9 6 4 5 3 7 9 1 6
 2 0 5 7 3 2 7 8 8 9 3 9 9 0 7 1 6 7 8 5 7 7 6 6 3 9 6 5 6 5 1 8 1 3 3 7 3
 3 3 7 7 6 6 0 8 1 4 6 6 2 8 8 4 1 5 8 9 4 1 4 3 1 3 9 0 6 5 3 9 0 0 8 4 8
 5 7 5 3 4 0 0 4 5 0 8 6 6 0 9 5 2 1 3 3 4 8 5 7 6 9 8 1 2 6 1 3 6 2 2 7 8
 0 4 9 2 0 5 0 3 5 8 8 2 3 5 6 9 0 1 6 6 1 2 7 6 7 1 6 4 1 7 7 0 0 9 8 8 0
 1 1 4 3 0 6 7 1 2 9 0 1 9 2 9 3 2 5 5 2 3 3 4 7 0 7 3 1 8 1 2 5 2 9 2 1 1
 2 5 0 8 9 6 4 7 5 7 4 7 4 7 4 1 4 3 7 0 8 3 0 0 5 8 2 7 0 6 9 7 1 7 3 0 6
 6 0 4 3 1 5 6 7 1 1 4 7 2 2 2 6 2 0 8 1 9 4 9 4 2 1 5 1 3 4 3 2 8 3 2 1 7
 3 4 1 8 2 3 5 7 2 5 5 6 

0.877

Even in Dev Set our Accuracy is **~ 88%** which **generalized** really well !
