In [399]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [400]:
data = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')

In [401]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [402]:
data = np.array(data)
m,n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
y_dev = data_dev[0]
x_dev = data_dev[1:n]
x_dev = x_dev/255.

data_train = data[1000:m].T
y_train = data_train[0]
x_train = data_train[1:n]
x_train = x_train/255.
print(x_train.shape)


(784, 41000)


In [403]:
y_train

array([4, 9, 1, ..., 8, 5, 5])

In [404]:
def initialize():
    w1 = np.random.rand(10,784) - 0.5
    b1 = np.random.rand(10,1) - 0.5
    w2 = np.random.rand(10,10) - 0.5
    b2 = np.random.rand(10,1) - 0.5
    return w1,b1,w2,b2

In [405]:
def ReLU(z):
    return np.maximum(z,0)

In [406]:
def softmax(z):
    return np.exp(z)/ sum(np.exp(z))

In [407]:
def forward_propogation(w1,b1,w2,b2,x):
    z1 = w1.dot(x) + b1
    a1 = ReLU(z1)
    z2 = w2.dot(a1)+ b2
    a2 = softmax(z2)
    return z1,a1,z2,a2

In [408]:
def deriv_ReLU(z):
    return z > 0;

In [409]:
def back_propogation(z1,a1,z2,a2,w1,w2,x,y):
    linear_y = np.zeros((y.size,y.max()+1))
    linear_y[np.arange(y.size),y] = 1
    linear_y = linear_y.T
    dz2 = a2 - linear_y
    dw2 = (1/m)*dz2.dot(a1.T)
    db2 = (1/m) *np.sum(dz2)
    dz1 = w2.T.dot(dz2) * deriv_ReLU(z1)
    dw1 = 1/m * dz1.dot(x.T)
    db1 = 1/m * np.sum(dz1)
    return dw1,db1,dw2,db2

In [410]:
def update_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha):
    w1 = w1 - alpha*dw1
    b1 = b1 - alpha*db1
    w2 = w2 - alpha*dw2
    b2 = b2 - alpha*db2
    return w1,b1,w2,b2

In [411]:
def get_predictions(a2):
    return np.argmax(a2,0)
def get_accuracy(predictions,y):
    print(predictions,y)
    return np.sum(predictions == y) / y.size

In [412]:
def gradient_descent(x,y,alpha,iterations):
    w1,b1,w2,b2 = initialize()
    for i in range(iterations):
        z1,a1,z2,a2 = forward_propogation(w1,b1,w2,b2,x)
        dw1,db1,dw2,db2 = back_propogation(z1,a1,z2,a2,w1,w2,x,y)
        w1,b1,w2,b2 = update_params(w1,b1,w2,b2,dw1,db1,dw2,db2,alpha)
        if i% 10 == 0:
            print("Iteration : ",i)
            print("Accuracy : ",get_accuracy(get_predictions(a2),y))
    return w1,b1,w2,b2
    
    

In [413]:
w1,b1,w2,b2 = gradient_descent(x_train,y_train,0.10,1000)

Iteration :  0
[9 8 5 ... 6 8 5] [4 9 1 ... 8 5 5]
Accuracy :  0.09107317073170731
Iteration :  10
[9 8 5 ... 6 9 5] [4 9 1 ... 8 5 5]
Accuracy :  0.11941463414634146
Iteration :  20
[9 8 5 ... 1 0 5] [4 9 1 ... 8 5 5]
Accuracy :  0.18253658536585365
Iteration :  30
[8 8 5 ... 1 0 5] [4 9 1 ... 8 5 5]
Accuracy :  0.2527317073170732
Iteration :  40
[4 8 1 ... 1 0 3] [4 9 1 ... 8 5 5]
Accuracy :  0.32558536585365855
Iteration :  50
[4 8 1 ... 5 0 3] [4 9 1 ... 8 5 5]
Accuracy :  0.3744390243902439
Iteration :  60
[4 8 1 ... 5 5 3] [4 9 1 ... 8 5 5]
Accuracy :  0.4188292682926829
Iteration :  70
[4 8 1 ... 5 5 3] [4 9 1 ... 8 5 5]
Accuracy :  0.4602439024390244
Iteration :  80
[4 9 1 ... 5 5 3] [4 9 1 ... 8 5 5]
Accuracy :  0.498
Iteration :  90
[9 9 1 ... 5 5 3] [4 9 1 ... 8 5 5]
Accuracy :  0.5281219512195122
Iteration :  100
[9 9 1 ... 5 5 3] [4 9 1 ... 8 5 5]
Accuracy :  0.5537804878048781
Iteration :  110
[9 9 1 ... 5 5 3] [4 9 1 ... 8 5 5]
Accuracy :  0.5756829268292682
Iteration : 

After 1000 Iterations **Test Accuracy ~ 88% **
